# Generated by Django 3.2 on 2021-04-21 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audiobook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Book title')),
                ('autor', models.CharField(max_length=100, verbose_name="Author's name")),
                ('narrator', models.CharField(max_length=100, verbose_name="Narrator's name")),
                ('duration', models.PositiveIntegerField(verbose_name="Song's duration")),
                ('uploaded_time', models.DateField(verbose_name='uploaded_time')),
            ],
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pd_name', models.CharField(max_length=100, verbose_name='Podcast name')),
                ('duration', models.PositiveIntegerField(verbose_name="Song's duration")),
                ('uploaded_time', models.DateField(verbose_name='uploaded_time')),
                ('host', models.CharField(max_length=100, verbose_name='Song name')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=100, verbose_name='Song name')),
                ('duration', models.PositiveIntegerField(verbose_name="Song's duration")),
                ('uploaded_time', models.DateField(verbose_name='uploaded_time')),
            ],
        ),
    ]
