# Generated by Django 3.2 on 2021-04-22 14:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('audiofile', '0002_auto_20210422_1112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audiobook',
            old_name='autor',
            new_name='author',
        ),
        migrations.AlterField(
            model_name='audiobook',
            name='uploaded_time',
            field=models.DateField(default=datetime.datetime(2021, 4, 22, 14, 31, 54, 27007, tzinfo=utc), verbose_name='uploaded_time'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='uploaded_time',
            field=models.DateField(default=datetime.datetime(2021, 4, 22, 14, 31, 54, 27007, tzinfo=utc), verbose_name='Uploaded time'),
        ),
        migrations.AlterField(
            model_name='song',
            name='uploaded_time',
            field=models.DateField(default=datetime.datetime(2021, 4, 22, 14, 31, 54, 27007, tzinfo=utc), verbose_name='uploaded_time'),
        ),
    ]
