# Generated by Django 3.2 on 2021-04-22 19:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('audiofile', '0004_auto_20210422_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiobook',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='audiobook',
            name='narrator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='audiobook',
            name='uploaded_time',
            field=models.DateField(default=datetime.datetime(2021, 4, 22, 19, 35, 57, 135662, tzinfo=utc), verbose_name='uploaded_time'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='podcast_host', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='participants',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='uploaded_time',
            field=models.DateField(default=datetime.datetime(2021, 4, 22, 19, 35, 57, 132663, tzinfo=utc), verbose_name='Uploaded time'),
        ),
        migrations.AlterField(
            model_name='song',
            name='uploaded_time',
            field=models.DateField(default=datetime.datetime(2021, 4, 22, 19, 35, 57, 132663, tzinfo=utc), verbose_name='uploaded_time'),
        ),
    ]
