# Generated by Django 3.2 on 2021-04-23 14:09

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('audiofile', '0006_auto_20210423_0109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='podcast',
            old_name='pd_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='audiobook',
            name='uploaded_time',
            field=models.DateField(default=datetime.datetime(2021, 4, 23, 14, 9, 0, 145035, tzinfo=utc), verbose_name='uploaded_time'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='host',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='podcast_host', to='account.user', verbose_name='Host name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='podcast',
            name='participants',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL, verbose_name='Participant names'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='uploaded_time',
            field=models.DateField(default=datetime.datetime(2021, 4, 23, 14, 9, 0, 145035, tzinfo=utc), verbose_name='Uploaded time'),
        ),
        migrations.AlterField(
            model_name='song',
            name='uploaded_time',
            field=models.DateField(default=datetime.datetime(2021, 4, 23, 14, 9, 0, 145035, tzinfo=utc), verbose_name='uploaded_time'),
        ),
    ]
