# Generated by Django 3.2 on 2021-04-24 10:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('audiofile', '0009_auto_20210424_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiobook',
            name='uploaded_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='uploaded_time'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='uploaded_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Uploaded time'),
        ),
        migrations.AlterField(
            model_name='song',
            name='uploaded_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='uploaded_time'),
        ),
    ]
